// For compute shader, register spaces are:
// Sampler: space0
// Texture: space0
// ReadOnlyStorageTex: space0
// ReadOnlyStorageBuf: space0
// RWTex: space1
// RWBuf: space1
// Uniform: space2

#include "fluid_solver_2d/mac_grid.hlsl"
#include "fluid_solver_2d/fluid_field_info.hlsl"

SamplerState vel_field_sampler : register(s0, space0);

Texture2D<float> prev_vel_field_u : register(t0, space0);
Texture2D<float> prev_vel_field_v : register(t1, space0);

Texture2D<float> prev_center_field : register(t2, space0);

RWTexture2D<float> curr_center_field : register(u0, space1);

[numthreads(8, 8, 1)] void main(uint3 thread_id : SV_DispatchThreadID)
{
    if (thread_id.x >= resolution + 1)
    {
        return;
    }
    if (thread_id.y >= resolution)
    {
        return;
    }

    FluidFieldInfo field_info;
    field_info.dx = dx;
    field_info.rdx = rdx;
    field_info.dt = dt;
    field_info.rdt = rdt;
    field_info.resolution = resolution;
    field_info.inv_res = inv_res;
    field_info.inv_res_plus_one = inv_res_plus_one;

    float2 curr_pos = ((float2)(thread_id.xy) + float2(0.5f, 0.5f)) * dx;

    float2 prev_vel_at_curr_pos = sample_vel_at_pos(prev_vel_field_u, prev_vel_field_v, vel_field_sampler, curr_pos, field_info);

    float2 prev_pos = curr_pos - prev_vel_at_curr_pos * dt;

    float2 prev_uv = prev_pos * rdx *inv_res;

    curr_center_field[thread_id.xy] = prev_center_field.SampleLevel(vel_field_sampler, prev_uv, 0);
}
