#include "fluid_solver_2d/mac_grid.hlsl"
#include "fluid_solver_2d/fluid_field_info.hlsl"
#include "fluid_solver_2d/presure_boundary_condition.hlsl"

Texture2D<float> vel_divergence_field : register(t0, space0);
Texture2D<float> prev_presure_field : register(t1, space0);

RWTexture2D<float> iter_presure_field : register(u0, space1);

[numthreads(8, 8, 1)] void main(uint3 thread_id : SV_DispatchThreadID)
{
    float p_l = get_presure_safe(int2((int)thread_id.x - 1, (int)thread_id.y), resolution, prev_presure_field);
    float p_r = get_presure_safe(int2((int)thread_id.x + 1, (int)thread_id.y), resolution, prev_presure_field);
    float p_b = get_presure_safe(int2((int)thread_id.x, (int)thread_id.y - 1), resolution, prev_presure_field);
    float p_u = get_presure_safe(int2((int)thread_id.x, (int)thread_id.y + 1), resolution, prev_presure_field);

    float d = vel_divergence_field[thread_id.xy];

    iter_presure_field[thread_id.xy] = (p_l + p_r + p_b + p_u - d * dx * dx) * 0.25f;
}
