#include "fluid_solver_2d/mac_grid.hlsl"
#include "fluid_solver_2d/fluid_field_info.hlsl"
#include "fluid_solver_2d/presure_boundary_condition.hlsl"

Texture2D<float> prev_vel_field_u : register(t0, space0);
Texture2D<float> prev_vel_field_v : register(t1, space0);

Texture2D<float> presure_field : register(t2, space0);

RWTexture2D<float> result_vel_field_u : register(u0, space1);
RWTexture2D<float> result_vel_field_v : register(u1, space1);

[numthreads(8, 8, 1)] void main(uint3 thread_id : SV_DispatchThreadID)
{
    if (thread_id.x >= resolution + 1)
    {
        return;
    }
    if (thread_id.y >= resolution)
    {
        return;
    }

    if (thread_id.x == 0 || thread_id.x == resolution)
    {
        result_vel_field_u[thread_id.xy] = 0;
        result_vel_field_v[thread_id.yx] = 0;
    }
    else
    {
        // For u:
        {
            float presure_l = get_presure_safe(int2((int)thread_id.x - 1, (int)thread_id.y), resolution, presure_field);
            float presure_r = get_presure_safe(int2((int)thread_id.x, (int)thread_id.y), resolution, presure_field);

            result_vel_field_u[thread_id.xy] = prev_vel_field_u[thread_id.xy] - inv_density * dt * (presure_r - presure_l) * rdx;
        }

        // For v:
        {
            float presure_b = get_presure_safe(int2((int)thread_id.y, (int)thread_id.x - 1), resolution, presure_field);
            float presure_u = get_presure_safe(int2((int)thread_id.y, (int)thread_id.x), resolution, presure_field);
            
            result_vel_field_v[thread_id.yx] = prev_vel_field_v[thread_id.yx] - inv_density * dt * (presure_u - presure_b) * rdx;
        }
    }
}
