RWTexture2D<float4> out_image : register(u0, space1);

cbuffer UBO : register(b0, space2)
{
    float ubo_time : packoffset(c0);
};

float2 complex_sqr(float2 z)
{
    return float2(z.x * z.x - z.y * z.y, 2.0f * z.x * z.y);
}

float complex_norm(float2 z)
{
    return z.x * z.x + z.y * z.y;
}

[numthreads(8, 8, 1)] void main(uint3 pixel_coord : SV_DispatchThreadID)
{
    float w, h;
    out_image.GetDimensions(w, h);

    float2 coord = pixel_coord.xy;

    float2 c = float2(-0.8f, 0.2f * cos(ubo_time * 2.0f));
    float2 z = float2(coord.x / w - 0.5f, coord.y / h - 0.5f) * 4.0f;

    float iterations = 0.0f;
    for (int i = 0; i < 50 && complex_norm(z) < 20.0f; ++i)
    {
        z = complex_sqr(z) + c;
        iterations += 1.0f;
    }

    float value = 1.0f - iterations * 0.02f;
    out_image[int2(coord)] = float4(value, value, value, 1.0f);
}
