#include "ray_tracing/camera.hlsl"
#include "ray_tracing/ray.hlsl"
#include "ray_tracing/math_constant.hlsl"
#include "ray_tracing/sphere.hlsl"

RWTexture2D<float4> out_image : register(u0, space1);

[numthreads(8, 8, 1)] void main(uint3 pixel_coord : SV_DispatchThreadID)
{
    float w, h;
    out_image.GetDimensions(w, h);

    Camera camera;
    Camera_InitViewport(camera, w, h, PI * (1.0f / 4.0f));
    Camera_InitPose(camera, float3(0.0f, 0.0f, -5.0f), float3(0.0f, 0.0f, 0.0f));

    Ray ray = Camera_GetRayByPixelUv(camera, pixel_coord.xy);

    Sphere sphere;
    sphere.center = float3(0.0f, 0.0f, 0.0f);
    sphere.radius = 1.0f;

    Intersection intersection = Sphere_Intersect(sphere, ray);

    float3 color = float3(0.0f, 0.0f, 0.0f);
    if (intersection.hit_time > 1e-4f && intersection.hit_time < 1e8f)
    {
        color = normalize(intersection.hit_pos - sphere.center) * 0.5f + 0.5f;
    }

    out_image[int2(pixel_coord.xy)] = float4(color, 1.0f);
}
